version: 2

before:
  hooks:
    - go mod tidy

builds:
  - main: ./cmd/gha-freeze
    binary: gha-freeze
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w
      - -X main.version={{.Version}}
      - -X github.com/thinesjs/gha-freeze/cmd/gha-freeze.version={{.Version}}

archives:
  - format: tar.gz
    name_template: >-
      {{ .ProjectName }}_
      {{- .Version }}_
      {{- if eq .Os "darwin" }}macOS
      {{- else }}{{ .Os }}{{ end }}_
      {{- .Arch }}
    format_overrides:
      - goos: windows
        format: zip
    files:
      - README.md
      - LICENSE*

checksum:
  name_template: 'checksums.txt'

snapshot:
  version_template: "{{ incpatch .Version }}-next"

changelog:
  sort: asc
  use: github
  filters:
    exclude:
      - '^docs:'
      - '^test:'
      - '^chore:'
      - '^ci:'
  groups:
    - title: Features
      regexp: '^feat:'
      order: 0
    - title: Bug Fixes
      regexp: '^fix:'
      order: 1
    - title: Others
      order: 999

release:
  github:
    owner: thinesjs
    name: gha-freeze
  draft: false
  prerelease: auto
  mode: append
  name_template: "v{{.Version}}"

# brews:
#   - repository:
#       owner: thinesjs
#       name: homebrew-tap
#       token: "{{ .Env.GITHUB_TOKEN }}"
#     directory: Formula
#     homepage: https://github.com/thinesjs/gha-freeze
#     description: Pin GitHub Actions to specific SHA commits
#     license: MIT
#     test: |
#       system "#{bin}/gha-freeze --version"
#     install: |
#       bin.install "gha-freeze"
